#include<stdio.h>
#include<conio.h>
#include<dos.h>
void main()
{
int col,row,len,i;
clrscr();
col=8;row=1;len=26;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");
     }

col=35;row=1;len=7;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ü");
     }

col=43;row=1;len=27;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");
     }

col=8;row=2;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("±");
     }

col=8;row=3;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=8;row=4;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=8;row=5;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=8;row=6;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=8;row=7;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=8;row=8;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=8;row=9;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=8;row=10;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=8;row=11;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=8;row=12;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=8;row=13;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=8;row=14;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=8;row=15;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

     /*ANSWER BOX*/

col=15;row=18;len=47;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ü");
     }

col=15;row=19;len=47;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("±");
     }

col=15;row=21;len=30;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=52;row=21;len=10;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=15;row=20;len=47;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=15;row=22;len=47;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=15;row=23;len=47;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");
     }

col=15;row=24;len=47;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("±");
     }

col=8;row=8;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");
     }

col=8;row=16;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");
     }

col=8;row=12;len=62;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");
     }

col=39;row=8;len=7;
gotoxy(col,row);
for(i=row;i<=row+len;i++)
     {
     gotoxy(col,i);
     textcolor(BLUE);
     cprintf("³");
     }


col=35;row=2;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("QUESTION");


col=35;row=3;len=7;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     //delay(110);
     cprintf("±");
     }

col=15;row=25;len=47;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");
     }

col=15;row=18;len=47;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");
     }

col=16;row=21;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("ANSWER(enter the alphabet):-");

col=16;row=23;
gotoxy(col,row);;
     textcolor(GREEN);
     cprintf("RESULT:-");


col=24;row=5;
gotoxy(col,row);
     textcolor(GREEN);
     delay(20);
     cprintf("1) Where is Fort William located?");

col=41;row=10;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[b] Goa");

col=9;row=10;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[a] Chennai");

col=9;row=14;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[c] KolKata");

col=41;row=14;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[d] Mysore");


		      int n;

		      col=48;row=21;
		      gotoxy(col,row);
		      //textcolor(GREEN);
		      scanf("%s",&n);

		      col=25;row=23;
		      gotoxy(col,row);
		      textcolor(GREEN);


		      switch(n)
			  {
			   case 'c':
			   cprintf("Your ans is correct.   ");
			   break;
			   default:
			   cprintf("Your ans is wrong.");
			   }

col=9;row=5;len=61;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}


col=9;row=10;len=29;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}


col=41;row=10;len=27;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}

col=9;row=14;len=27;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}

col=41;row=14;len=29;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}

col=25;row=23;len=30;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {gotoxy(i,row);
    textcolor(BLUE);
    delay(20);
    cprintf("Û");}

col=48;row=21;len=3;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {gotoxy(i,row);
    textcolor(GREEN);
    delay(20);
    cprintf(" ");}

col=22;row=5;
gotoxy(col,row);
     textcolor(GREEN);
     delay(20);
     cprintf("2) Who is the author of Harry Potter?");

col=41;row=10;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[b] Leo Lionni");

col=9;row=10;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[a] H.A. Rey");

col=9;row=14;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[c] P.D. Eastman");

col=41;row=14;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[d] J.K. Rowling");


		      col=48;row=21;
		      gotoxy(col,row);
		      //textcolor(GREEN);
		      scanf("%s",&n);

		      col=25;row=23;
		      gotoxy(col,row);
		      textcolor(GREEN);


		      switch(n)
			  {
			   case 'd':
			   cprintf("Your ans is correct.   ");
			   break;
			   default:
			   cprintf("Your ans is wrong.");
			   }

col=9;row=5;len=61;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}


col=9;row=10;len=29;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}


col=41;row=10;len=27;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}

col=9;row=14;len=27;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}

col=41;row=14;len=29;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}

col=25;row=23;len=30;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {gotoxy(i,row);
    textcolor(BLUE);
    delay(20);
    cprintf("Û");}

col=48;row=21;len=3;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {gotoxy(i,row);
    textcolor(GREEN);
    delay(20);
    cprintf(" ");}

col=22;row=5;
gotoxy(col,row);
     textcolor(GREEN);
     delay(20);
     cprintf("3) The Komark Temple is dedicated to?");

col=41;row=10;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[b] Vishnu");

col=9;row=10;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[a] Shiva ");

col=9;row=14;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[c] Krishna");

col=41;row=14;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[d] Sun-God");


		      col=48;row=21;
		      gotoxy(col,row);
		      //textcolor(GREEN);
		      scanf("%s",&n);

		      col=25;row=23;
		      gotoxy(col,row);
		      textcolor(GREEN);


		      switch(n)
			  {
			   case 'd':
			   cprintf("Your ans is correct.   ");
			   break;
			   default:
			   cprintf("Your ans is wrong.");
			   }

col=9;row=5;len=61;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}


col=9;row=10;len=29;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}


col=41;row=10;len=27;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}

col=9;row=14;len=27;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}

col=41;row=14;len=29;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}

col=25;row=23;len=30;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {gotoxy(i,row);
    textcolor(BLUE);
    delay(20);
    cprintf("Û");}

col=48;row=21;len=3;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {gotoxy(i,row);
    textcolor(GREEN);
    delay(20);
    cprintf(" ");}

col=21;row=5;
gotoxy(col,row);
     textcolor(GREEN);
     delay(20);
     cprintf("4) September 27 is celebrated every year as ?");

col=41;row=10;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[b] Teacher's day");

col=9;row=10;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[a] National integration day");

col=9;row=14;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[c] World tourism day");

col=41;row=14;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[d] International literacy day");


		      col=48;row=21;
		      gotoxy(col,row);
		      //textcolor(GREEN);
		      scanf("%s",&n);

		      col=25;row=23;
		      gotoxy(col,row);
		      textcolor(GREEN);


		      switch(n)
			  {
			   case 'c':
			   cprintf("Your ans is correct.   ");
			   break;
			   default:
			   cprintf("Your ans is wrong.");
			   }
col=9;row=5;len=61;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}


col=9;row=10;len=29;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}


col=41;row=10;len=27;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}

col=9;row=14;len=27;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}

col=41;row=14;len=29;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(20);
     cprintf("Û");}

col=25;row=23;len=30;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {gotoxy(i,row);
    textcolor(BLUE);
    delay(20);
    cprintf("Û");}

col=48;row=21;len=3;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {gotoxy(i,row);
    textcolor(GREEN);
    delay(20);
    cprintf(" ");}

col=18;row=5;
gotoxy(col,row);
     textcolor(GREEN);
     delay(20);
     cprintf("5) Name of tallest building in the world ?");

col=41;row=10;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[b] Chase tower");

col=9;row=10;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[a] Burj Khalifa");

col=9;row=14;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[c] Taipei 101");

col=41;row=14;
gotoxy(col,row);
     textcolor(GREEN);
     cprintf("[d] Central Plaza ");


		      col=48;row=21;
		      gotoxy(col,row);
		      //textcolor(GREEN);
		      scanf("%s",&n);

		      col=25;row=23;
		      gotoxy(col,row);
		      textcolor(GREEN);


		      switch(n)
			  {
			   case 'a':
			   cprintf("Your ans is correct.   ");
			   break;
			   default:
			   cprintf("Your ans is wrong.");
			   }

col=9;row=5;len=61;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(10);
     cprintf("Û");}


col=9;row=10;len=29;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(10);
     cprintf("Û");}


col=41;row=10;len=27;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(10);
     cprintf("Û");}

col=9;row=14;len=27;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(10);
     cprintf("Û");}

col=41;row=14;len=29;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
     {gotoxy(i,row);
     textcolor(BLUE);
     delay(10);
     cprintf("Û");}

col=25;row=23;len=30;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {gotoxy(i,row);
    textcolor(BLUE);
    delay(10);
    cprintf("Û");}

col=48;row=21;len=3;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {gotoxy(i,row);
    textcolor(GREEN);
    delay(10);
    cprintf(" ");}

col=34;row=6;//len=40;
gotoxy(col,row);
//for(i=col;i<=col+len;i++)
     //gotoxy(i,row);
     textcolor(GREEN);
     //delay(10);
     cprintf("GAME OVER");


getch();
}